const Stack = createNativeStackNavigator(); import * as React from "react"; import { NavigationContainer } from "@react-navigation/native"; import { useFonts } from "expo-font"; import HomeScreen from "./screens/HomeScreen"; import LoginScreen from "./screens/LoginScreen"; import AllLoansScreen from "./screens/AllLoansScreen"; import LoanDetailsScreen from "./screens/LoanDetailsScreen"; import AllDisputesScreen from "./screens/AllDisputesScreen"; import AllInvestmentsScreen from "./screens/AllInvestmentsScreen"; import LoanStatementScreen from "./screens/LoanStatementScreen"; import LoanHistoryScreen from "./screens/LoanHistoryScreen"; import LoanTermsScreen from "./screens/LoanTermsScreen"; import FormTermsScreen from "./screens/FormTermsScreen"; import FormDisputeScreen from "./screens/FormDisputeScreen"; import DisputeDetailsScreen from "./screens/DisputeDetailsScreen"; import DisputeResolveScreen from "./screens/DisputeResolveScreen"; import GlossaryScreen from "./screens/GlossaryScreen"; import InterestScreen from "./screens/InterestScreen";

import { createNativeStackNavigator } from "@react-navigation/native-stack"; import { View, Text, Pressable, TouchableOpacity } from "react-native";

const App = () => { const [hideSplashScreen, setHideSplashScreen] = React.useState(true);

const [fontsLoaded, error] = useFonts({ "Inter-Regular": require("./assets/fonts/Inter-Regular.ttf"), "Inter-Medium": require("./assets/fonts/Inter-Medium.ttf"), });

if (!fontsLoaded && !error) { return null; }

return ( <> <NavigationContainer> {hideSplashScreen ? ( <Stack.Navigator screenOptions={{ headerShown: false }}> <Stack.Screen name="HomeScreen" component={HomeScreen} options={{ headerShown: false }} /> <Stack.Screen name="LoginScreen" component={LoginScreen} options={{ headerShown: false }} /> <Stack.Screen name="AllLoansScreen" component={AllLoansScreen} options={{ headerShown: false }} /> <Stack.Screen name="LoanDetailsScreen" component={LoanDetailsScreen} options={{ headerShown: false }} /> <Stack.Screen name="AllDisputesScreen" component={AllDisputesScreen} options={{ headerShown: false }} /> <Stack.Screen name="AllInvestmentsScreen" component={AllInvestmentsScreen} options={{ headerShown: false }} /> <Stack.Screen name="LoanStatementScreen" component={LoanStatementScreen} options={{ headerShown: false }} /> <Stack.Screen name="LoanHistoryScreen" component={LoanHistoryScreen} options={{ headerShown: false }} /> <Stack.Screen name="LoanTermsScreen" component={LoanTermsScreen} options={{ headerShown: false }} /> <Stack.Screen name="FormTermsScreen" component={FormTermsScreen} options={{ headerShown: false }} /> <Stack.Screen name="FormDisputeScreen" component={FormDisputeScreen} options={{ headerShown: false }} /> <Stack.Screen name="DisputeDetailsScreen" component={DisputeDetailsScreen} options={{ headerShown: false }} /> <Stack.Screen name="DisputeResolveScreen" component={DisputeResolveScreen} options={{ headerShown: false }} /> <Stack.Screen name="GlossaryScreen" component={GlossaryScreen} options={{ headerShown: false }} /> <Stack.Screen name="InterestScreen" component={InterestScreen} options={{ headerShown: false }} /> </Stack.Navigator> ) : null} </NavigationContainer> </> ); }; export default App;